sudo: required

services:
  - docker

language: node_js

install:
  - npm install -g grunt-cli
script: grunt build

after_success:
  - docker build -t $DOCKER_USERNAME/nginx .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/nginx
