sudo: required
services:
  - docker
language: node_js
before_script:
  - npm install -g grunt-cli
script: grunt build
after_success:
  - docker build -t $DOCKER_IMAGE_NAME:$TRAVIS_JOB_NUMBER .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE_NAME
