sudo: required
services:
  - docker
language: node_js
before_script:
  - npm install -g grunt-cli
script: grunt build
after_success:
  - docker build -t $DOCKER_IMAGE_NAME:$TRAVIS_JOB_NUMBER .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag $$DOCKER_IMAGE_NAME:$TRAVIS_JOB_NUMBER DOCKER_IMAGE_NAME:latest
  - docker push $DOCKER_IMAGE_NAME
deploy:
  provider:
    provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: marvin.charles@gmail.com
  password: $CLOUD_FOUNDRY_PASSWORD
  organization: threetwoonefive
  space: development
  edge: true
