export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_USER: 'LOGOUT_USER',
    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    TOKEN_LOGIN_SUCCESS: 'TOKEN_LOGIN_SUCCESS', 
    TOKEN_LOGIN_FAILURE: 'TOKEN_LOGIN_FAILURE', 
    TOKEN_LOGIN_REQUESTED: 'TOKEN_LOGIN_REQUESTED'
};
