export const INSTRUCTORS_REQUESTED = 'INSTRUCTORS_REQUESTED';
export const INSTRUCTORS_REQUEST_SUCCESS = 'INSTRUCTORS_REQUEST_SUCCESS';
export const INSTRUCTORS_REQUEST_FAILURE = 'INSTRUCTORS_REQUEST_FAILURE';
